In [3]:
import numpy as np
import random

In [34]:
def ndim(n):
    mtrx_sqrt_trivial = np.zeros((n+1, n)) #burada burada n = 5 sample sayisi, N=3 boyut, bu sqrtlerin atanacağı matrix
    mtrx = np.zeros((n,n)) #bu ise normal degerlerin atanacagi matrix
    mtrx_sqrt_trivial[0] = np.ones((1,n))
    r_1 = np.zeros((1,n))
       

    for q in range(n-1):
        srt=np.array([])
        r_2 = mtrx_sqrt_trivial[0] - r_1
        print(r_1)
        for i in range(n): #burada range n olacak
            tek = random.uniform(0, r_2[0][i])
            srt = np.append(srt,tek)
        mtrx_sqrt_trivial[q+1] = srt
        r_1 = srt + r_1
        
    mtrx_sqrt_trivial[n] = 1 - r_1
    mtrx_sqrt = np.delete(mtrx_sqrt_trivial,0,0)
    
    mtrx = np.sqrt(mtrx_sqrt)
    
    for u in range(n):
        arr = [(np.random.randint(0,2)*2-1) for i in range(n)]
        mtrx[u] = mtrx[u] * arr
    
    
    return mtrx_sqrt

In [35]:
deneme = ndim(5)

[[0. 0. 0. 0. 0.]]
[[0.22085815 0.49703407 0.01917367 0.19965369 0.41624019]]
[[0.74739508 0.49969366 0.07699486 0.99645334 0.95133291]]
[[0.9412711  0.93209227 0.44752149 0.99674093 0.97214709]]


In [36]:
deneme[0][1]+deneme[1][1]+deneme[2][1]+deneme[3][1]+deneme[4][1]

1.0

In [19]:
deneme

array([[0.20597083, 0.14932924, 0.88493196, 0.11579005, 0.81736115],
       [0.30083817, 0.41585258, 0.06176838, 0.84445618, 0.04613444],
       [0.25922719, 0.09956874, 0.01232639, 0.02487494, 0.04957423],
       [0.15648739, 0.24579372, 0.01277256, 0.0104219 , 0.01117398],
       [0.07747642, 0.08945573, 0.02820071, 0.00445693, 0.0757562 ]])